export const skillsOptions = [
  "Web Development",
  "Frontend Frameworks",
  "Backend Development",
  "Mobile App Development",
  "Game Development",
  "Data Analysis",
  "Data Science & Machine Learning",
  "Artificial Intelligence / Deep Learning",
  "Natural Language Processing",
  "Big Data Tools",
  "Cloud Computing",
  "DevOps & CI/CD",
  "Cybersecurity",
  "UI/UX Design",
  "Graphic Design",     
  "Digital Marketing",
  "SEO Optimization",
  "Content Creation",
  "Video Editing & Production",
  "Project Management",
  "Database Management",
  "API Development & Integration",
  "Robotics / IoT",
  "Embedded Systems",
  "Blockchain Development",
  "Technical Writing / Documentation",
  "AR/VR Development",
  "E-commerce Development",

  // Add more skills if needed
];
